// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5HVQc-_b8cTZl-6oVb7R7osQTesA635k',
    appId: '1:805920219933:web:c183061fbf4849b8da77f4',
    messagingSenderId: '805920219933',
    projectId: 'algeoapp-144',
    authDomain: 'algeoapp-144.firebaseapp.com',
    storageBucket: 'algeoapp-144.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9mqg_qDSDFGfaybTrh0S9eBLncFHH1AY',
    appId: '1:805920219933:android:ca81551d7b6db024da77f4',
    messagingSenderId: '805920219933',
    projectId: 'algeoapp-144',
    storageBucket: 'algeoapp-144.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmlGDhWN9GIXzuJPJ6rEPmHuyULG88298',
    appId: '1:805920219933:ios:cffa9c7578844a36da77f4',
    messagingSenderId: '805920219933',
    projectId: 'algeoapp-144',
    storageBucket: 'algeoapp-144.firebasestorage.app',
    iosBundleId: 'com.example.realtimeMessageCalling',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5HVQc-_b8cTZl-6oVb7R7osQTesA635k',
    appId: '1:805920219933:web:ad23983021feecd5da77f4',
    messagingSenderId: '805920219933',
    projectId: 'algeoapp-144',
    authDomain: 'algeoapp-144.firebaseapp.com',
    storageBucket: 'algeoapp-144.firebasestorage.app',
  );
}
